name: Unit Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install --frozen-lockfile
      - name: Lint
        run: npm run lint
      - name: ls-lint
        run: npm run ls-lint
      - name: Test
        run: npm run test
      # - name: deploy-doc
      #   run: npm run docs-build-deploy
